---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config-map
data:
  application.yaml:
  {{ .Files.Get "config/application-template.txt"
  | replace "{{POSTGRES_HOST}}"  (printf "%s-postgresql-hl" .Release.Name)
  | replace "{{POSTGRES_PORT}}" .Values.global.postgresql.service.ports.postgresql
  | replace "{{POSTGRES_DB}}"  .Values.global.postgresql.auth.database
  | replace "{{POSTGRES_USER}}" .Values.global.postgresql.auth.username
  | replace "{{POSTGRES_PASSWORD}}" .Values.global.postgresql.auth.password
  | toYaml
  | indent 4
  }}
 
